name: flutter_animaciones_notificaciones
description: "A new Flutter project."
publish_to: 'none' # Evita la publicación accidental a pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"  # Usa comillas para evitar errores de formato

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  # Dependencias principales
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_staggered_animations: ^1.1.1
  provider: ^6.1.1
  intl: ^0.19.0
  timezone: ^0.10.1
  permission_handler: ^11.3.0
  flutter_local_notifications: ^19.2.1
  shared_preferences: ^2.0.15
  http: ^1.2.0

  # Hive (Base de datos local)
  hive: ^2.0.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Generadores de código (¡IMPORTANTE: deben estar en dev_dependencies!)
  build_runner: ^2.4.9
  hive_generator: ^2.0.1
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  generate: true