name: flutter_animaciones_notificaciones
description: "A new Flutter project."
publish_to: 'none' # Evita publicación accidental

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Dependencias principales
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_staggered_animations: ^1.1.1
  provider: ^6.1.1
  intl: ^0.19.0
  timezone: ^0.10.1
  permission_handler: ^11.3.0
  flutter_local_notifications: ^19.2.1
  shared_preferences: ^2.0.15
  http: ^1.2.0

  # Base de datos local
  hive: ^2.0.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1
  mockito: ^5.4.2

flutter_launcher_icons: # Configuración actualizada
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/tarea.jpeg" # Ruta exacta de tu imagen
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/ # Asegura que Flutter reconozca la carpeta